# Python Library: Numpy

In [1]:
import numpy as np

In [2]:
#creating a list
l1 = [2,4,5,6,7]

In [4]:
#creating an array
n1=np.array(l1)

In [5]:
n1

array([2, 4, 5, 6, 7])

In [12]:
type(n1)

numpy.ndarray

In [14]:
n2=np.array([[2,3,4,6,7],[8,1,4,2,4]])

In [8]:
n2

array([list([2, 3, 4, 6, 7]), list([0, 1, 4, 2, 4, 6])], dtype=object)

In [15]:
type(n2)

numpy.ndarray

In [16]:
n3=np.zeros((2,3))

In [17]:
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
type(n3)

numpy.ndarray

In [20]:
n4=np.zeros((10,3))

In [21]:
n4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
n5=np.full((5,4),46)

In [24]:
n5

array([[46, 46, 46, 46],
       [46, 46, 46, 46],
       [46, 46, 46, 46],
       [46, 46, 46, 46],
       [46, 46, 46, 46]])

In [28]:
n6=np.arange(10,40)

In [29]:
n6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [31]:
n7=np.arange(10,50,5)

In [32]:
n7

array([10, 15, 20, 25, 30, 35, 40, 45])

In [38]:
n8=np.random.randint(100,200,10)

In [39]:
n8

array([117, 141, 108, 111, 117, 178, 162, 179, 176, 183])

In [ ]:
#Changing the shape of Numpy array

In [41]:
n1=np.array([[2,5,6,8,9],[7,9,5,4,2]])

In [42]:
n1.shape

(2, 5)

In [43]:
n1.shape =(5,2)

In [44]:
n1.shape

(5, 2)

In [56]:
##Joining Numpy Arrays
n1=np.array([45,78,98,34,45])
n2=np.array([77,99,44,34,45])

In [57]:
np.vstack((n1,n2))

array([[45, 78, 98, 34, 45],
       [77, 99, 44, 34, 45]])

In [58]:
np.hstack((n1,n2))

array([45, 78, 98, 34, 45, 77, 99, 44, 34, 45])

In [59]:
np.column_stack((n1,n2))

array([[45, 77],
       [78, 99],
       [98, 44],
       [34, 34],
       [45, 45]])

In [61]:
##Numpy intersection and difference
np.intersect1d(n1,n2)

array([34, 45])

In [63]:
np.setdiff1d(n1,n2)

array([78, 98])

In [64]:
np.setdiff1d(n2,n1)

array([44, 77, 99])

In [66]:
#Numpy Array math
n1=np.array([35,45])
n2=np.array([20,40])

In [68]:
np.sum([n1,n2])

140

In [70]:
np.sum([n1,n2],axis=0)

array([55, 85])

In [71]:
np.sum([n1,n2], axis=0)

array([55, 85])

In [ ]:
#Basic arthematic

In [72]:
n1=np.array([10,20,30])
n1=n1+2
n1

array([12, 22, 32])

In [74]:
n1=np.array([10,20,30])
n1=n1*2
#n1=n1/2
#n1=n1-2
n1

array([20, 40, 60])

In [75]:
#Numpy math function
#mean, median, st div

In [76]:
n1=np.random.randint(1,40,10)

In [77]:
n1

array([13, 21, 24, 38, 35, 26,  9, 27, 18, 13])

In [78]:
np.mean(n1)

22.4

In [79]:
np.median(n1)

22.5

In [80]:
np.std(n1)

9.035485598461214

In [85]:
##Saving Numpy array
n1=np.array([99,88,77,66,55])
np.save('my_numpy',n1)

In [87]:
n2=np.load('my_numpy.npy')
n2

array([99, 88, 77, 66, 55])